name: SD Course Check
on: [ push, pull_request ]
jobs:
    test:
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Check out repository code
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'zulu'
                    java-version: '11'
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
            -   name: Build with Gradle
                run: ./gradlew test build -x test -x detekt
            -   name: Test with Gradle
                run: ./gradlew test
            -   name: Upload a test report
                if: ${{ always() }}
                uses: actions/upload-artifact@v2
                with:
                    name: test-report-${{ matrix.os }}
                    path: build/reports/tests/test
    style:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out repository code
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'zulu'
                    java-version: '11'
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
            -   name: Check style
                if: ${{ always() }}
                id: check_style
                run: ./gradlew detekt
            -   name: Upload a linter report
                if: ${{ steps.check_style.conclusion == 'failure' }}
                uses: actions/upload-artifact@v2
                with:
                    name: linter-report
                    path: build/reports/detekt
    test-coverage:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out repository code
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'zulu'
                    java-version: '11'
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
            -   name: Test with Gradle
                run: ./gradlew test
            -   name: Check test coverage with Gradle
                if: ${{ always() }}
                run: ./gradlew jacocoTestCoverageVerification
            -   name: Create a test coverage report
                if: ${{ always() }}
                id: coverage_report
                run: ./gradlew jacocoTestReport
            -   name: Upload a test coverage report
                if: ${{ always() }}
                uses: actions/upload-artifact@v2
                with:
                    name: jacoco-html-report
                    path: build/jacocoHtml
            -   name: Upload a test coverage report to Codecov
                if: ${{ always() }}
                uses: codecov/codecov-action@v2
                with:
                    files: build/reports/jacoco/test/jacocoTestReport.xml
